In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [54]:
dataset=pd.read_csv(r'C:\Users\Admin\Desktop\Python Code\tmdb_5000_movies.csv')

In [55]:
dataset

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [56]:
dataset.iloc[0:0,0:]

Empty DataFrame
Columns: [budget, genres, homepage, id, keywords, original_language, original_title, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, vote_average, vote_count]
Index: []

In [57]:
dataset=dataset.drop(['budget','homepage','original_language','original_title','popularity','production_companies','production_countries','release_date','revenue','runtime','spoken_languages','status','tagline','vote_average','vote_count'],axis=1)

In [58]:
dataset.iloc[0:0,0:]

Empty DataFrame
Columns: [genres, id, keywords, overview, title]
Index: []

In [59]:
dataset

,genres,id,keywords,overview,title
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter
...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,El Mariachi
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],A newlywed couple's honeymoon is upended by th...,Newlyweds
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered"
4801,[],126186,[],When ambitious New York attorney Sam is sent t...,Shanghai Calling
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,My Date with Drew

In [60]:
dataset.genres.iloc[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [61]:
import ast

In [62]:
def keyname(obj):
    y=[]
    for i in ast.literal_eval(obj):
        name=i['name']
        y.append(name)
    return y

In [63]:
dataset['genres']=dataset['genres'].apply(keyname)

In [64]:
dataset.keywords.iloc[0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [65]:
def keyname2(obj2):
    y2=[]
    for i in ast.literal_eval(obj2):
        name2=i['name']
        y2.append(name2)
    return y2

In [66]:
dataset['keywords']=dataset['keywords'].apply(keyname2)

In [75]:
dataset.isnull().sum()

genres      0
id          0
keywords    0
overview    0
title       0
dtype: int64

In [76]:
dataset.overview.iloc[0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [77]:
dataset['overview']=dataset['overview'].apply(lambda x:x.split())

AttributeError: 'list' object has no attribute 'split'

In [78]:
dataset['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [83]:
dataset['keywords']=dataset['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [84]:
dataset['genres']=dataset['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [85]:
dataset['tags']=dataset['genres']+dataset['keywords']+dataset['overview']

In [86]:
dataset

,genres,id,keywords,overview,title,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]",9367,"[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[Action, Crime, Thriller, unitedstatesâ€“mexicob..."
4799,"[Comedy, Romance]",72766,[],"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,"[Comedy, Romance, A, newlywed, couple's, honey..."
4800,"[Comedy, Drama, Romance, TVMovie]",231617,"[date, loveatfirstsight, narration, investigat...","[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4801,[],126186,[],"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,[Documentary],25975,"[obsession, camcorder, crush, dreamgirl]","[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [91]:
dataset=dataset.drop(['keywords','overview','genres'],axis=1)

In [92]:
dataset

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4798,9367,El Mariachi,"[Action, Crime, Thriller, unitedstatesâ€“mexicob..."
4799,72766,Newlyweds,"[Comedy, Romance, A, newlywed, couple's, honey..."
4800,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [93]:
dataset['tags'][0]

['Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [94]:
dataset['tags']=dataset['tags'].apply(lambda x:" ".join(x))

In [95]:
dataset['tags'][0]

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [96]:
from sklearn.feature_extraction.text import CountVectorizer

In [97]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [98]:
vectors=cv.fit_transform(dataset['tags']).toarray()

In [99]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [100]:
from sklearn.metrics.pairwise import cosine_similarity

In [101]:
similarity=cosine_similarity(vectors)

In [102]:
similarity

array([[1.        , 0.09583148, 0.06277648, ..., 0.02465568, 0.0270666 ,
        0.        ],
       [0.09583148, 1.        , 0.07018624, ..., 0.02756589, 0.        ,
        0.        ],
       [0.06277648, 0.07018624, 1.        , ..., 0.02708645, 0.        ,
        0.        ],
       ...,
       [0.02465568, 0.02756589, 0.02708645, ..., 1.        , 0.07007128,
        0.04732485],
       [0.0270666 , 0.        , 0.        , ..., 0.07007128, 1.        ,
        0.05195243],
       [0.        , 0.        , 0.        , ..., 0.04732485, 0.05195243,
        1.        ]])

In [104]:
sorted(similarity[0],reverse=True)

[1.0,
 0.2732295333235123,
 0.264575131106459,
 0.2553999031169147,
 0.2480694691784169,
 0.24688535993934702,
 0.24397501823713333,
 0.24053511772118194,
 0.24053511772118194,
 0.23904572186687872,
 0.23904572186687872,
 0.23199266800191018,
 0.2267786838055363,
 0.2258769757263128,
 0.2253744679276044,
 0.2238868314198225,
 0.22190115272469205,
 0.22190115272469205,
 0.21971768720102058,
 0.2162249910469341,
 0.2162249910469341,
 0.2114722130550724,
 0.21128856368212912,
 0.20701966780270628,
 0.2059714602177749,
 0.2038588765750502,
 0.19920476822239894,
 0.19889806323953876,
 0.1980534816610477,
 0.1980534816610477,
 0.1980534816610477,
 0.19518001458970666,
 0.19518001458970666,
 0.19518001458970663,
 0.19477964490741226,
 0.1938916835823703,
 0.1938916835823703,
 0.1932024558334913,
 0.1916629694999819,
 0.18946618668626836,
 0.18946618668626836,
 0.18946618668626833,
 0.18946618668626833,
 0.1889822365046136,
 0.18832944617230335,
 0.18832944617230335,
 0.18832944617230335,
 0.18708286933869706,
 0.1858536462519902,
 0.18478728707195913,
 0.1825741858350554,
 0.18257418583505536,
 0.18070158058105024,
 0.17928429140015903,
 0.17837651700316892,
 0.1765469659009499,
 0.1763834207376394,
 0.17622684421256032,
 0.17622684421256032,
 0.17457431218879388,
 0.173137462139922,
 0.17251638983558856,
 0.17142857142857143,
 0.16903085094570333,
 0.1690308509457033,
 0.1690308509457033,
 0.16903085094570328,
 0.1673320053068151,
 0.16574838603294897,
 0.16574838603294897,
 0.1656833739159028,
 0.16452254913212452,
 0.16398401233815754,
 0.16239958858823,
 0.16239958858823,
 0.1610152971798826,
 0.16035674514745463,
 0.16035674514745463,
 0.15971914124998493,
 0.15649215928719032,
 0.15511334686589623,
 0.15511334686589623,
 0.1546617786679401,
 0.1546617786679401,
 0.15430334996209188,
 0.15430334996209188,
 0.15430334996209188,
 0.15430334996209188,
 0.15179418517972906,
 0.15149527937243176,
 0.15118578920369088,
 0.15118578920369088,
 0.15118578920369088,
 0.15118578920369088,
 0.14953343588376802,
 0.1494035761667992,
 0.1494035761667992,
 0.14907119849998596,
 0.14793410181646136,
 0.14754222271266348,
 0.14712247158412495,
 0.14712247158412492,
 0.14675987714106856,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.14488358652488853,
 0.14414999403128942,
 0.14414999403128942,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14098147537004826,
 0.14098147537004826,
 0.14098147537004826,
 0.14098147537004826,
 0.1406421692815486,
 0.1406421692815486,
 0.13930903806377162,
 0.13930903806377162,
 0.1389425035941821,
 0.1389425035941821,
 0.1389425035941821,
 0.1384849529435629,
 0.13848495294356286,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13710212427677043,
 0.13552618543578768,
 0.13552618543578768,
 0.13552618543578768,
 0.13552618543578768,
 0.13533299049019168,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.1336306209562122,
 0.1336306209562122,
 0.13259870882635919,
 0.13259870882635919,
 0.13199091933711365,
 0.1309307341415954,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.1301200097264711,
 0.1301200097264711,
 0.12985309660494151,
 0.12888481555661674,
 0.12888481555661674,
 0.12888481555661674,
 0.12880163722232754,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12741179785940637,
 0.12741179785940637,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.12598815766974242,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12461119656980671,
 0.1246111965698067,
 0.1246111965698067,
 0.12461119656980668,
 0.12344267996967351,
 0.12344267996967351,
 0.12327841818038447,
 0.12298800925361816,
 0.12298800925361816,
 0.12209353913347193,
 0.12198750911856666,
 0.12198750911856666,
 0.12198750911856665,
 0.12198750911856665,
 0.12143534814378325,
 0.12143534814378325,
 0.12143534814378325,
 0.12143534814378325,
 0.12143534814378325,
 0.12121830534626526,
 0.12073632210407378,
 0.1203616281427559,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.1183452670827877,
 0.1178966237837789,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11501092655705902,
 0.11501092655705902,
 0.11501092655705902,
 0.11428571428571428,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11396057645963795,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276816,
 0.1129384878631564,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11194341570991125,
 0.11194341570991125,
 0.11115400287534567,
 0.1109741904046188,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11002971203391539,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10910894511799618,
 0.10826639239215334,
 0.10826639239215334,
 0.10821091383745127,
 0.10811249552346708,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346705,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10647942749998995,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10460520656316097,
 0.10432810619146021,
 0.10432810619146021,
 0.10432810619146021,
 0.10432810619146021,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10101525445522105,
 0.10079052613579392,
 0.10079052613579392,
 0.09968895725584537,
 0.09968895725584535,
 0.09968895725584535,
 0.09960238411119947,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.09944903161976938,
 0.09862273454430757,
 0.09862273454430757,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09694584179118515,
 0.09658905768325902,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09569487529386908,
 0.09569487529386908,
 0.09467621366623016,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09287269204251442,
 0.09287269204251442,
 0.09287269204251442,
 0.09287269204251442,
 0.09276773134741387,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09221388919541468,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09116846116771035,
 0.09116846116771035,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.089554732567929,
 0.089554732567929,
 0.089554732567929,
 0.08877935232369503,
 0.08877935232369503,
 0.08877935232369503,
 0.08859623899229174,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047495,
 0.0880237696271323,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.086568731069961,
 0.08586775814821836,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.08518354199999197,
 0.08518354199999197,
 0.08518354199999197,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08386278693775347,
 0.08386278693775347,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.0832250378576479,
 0.08322503785764788,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08139569275564795,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.07985957062499248,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07813453848974923,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.0751248226425348,
 0.07476671794188403,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07248803762927497,
 0.07248803762927497,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07166893746324661,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.0692377343236081,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423541,
 0.06900655593423541,
 0.06837634587578277,
 0.06837634587578277,
 0.06837634587578276,
 0.06776309271789384,
 0.06776309271789384,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06716604942594674,
 0.06716604942594674,
 0.06716604942594674,
 0.06716604942594674,
 0.06658451424277127,
 0.06658451424277127,
 0.06658451424277127,
 0.06658451424277127,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.0654653670707977,
 0.0654653670707977,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06492654830247076,
 0.06492654830247076,
 0.06492654830247074,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06250763079179938,
 0.06195121541733006,
 0.06195121541733006,
 0.06195121541733006,
 0.06195121541733006,

In [134]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x: x[1])[1:6]

[(539, 0.2732295333235123),
 (1191, 0.264575131106459),
 (507, 0.2553999031169147),
 (1213, 0.2480694691784169),
 (260, 0.24688535993934702)]

In [ ]:
dataset[dataset['title']=='Avatar'].index[0]

In [165]:
(sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x: x[1])[1:6])

[(539, 0.2732295333235123),
 (1191, 0.264575131106459),
 (507, 0.2553999031169147),
 (1213, 0.2480694691784169),
 (260, 0.24688535993934702)]

In [169]:
def recommand(movie):
    movie_index_similarity=dataset[dataset['title']==movie].index[0]
    movie_index_title=(sorted(list(enumerate(similarity[movie_index_similarity])),reverse=True,key=lambda x: x[1])[1:6])
    for i in movie_index_title:
        name=dataset.iloc[i[0]].title
        print(name)
        # print(i)

In [171]:
recommand('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Aliens vs Predator: Requiem
Ender's Game

In [173]:
recommand('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman & Robin
Batman v Superman: Dawn of Justice